
version: '3.7'

services:
  server:
    image: rajivkumawat3/ecom_server   #else use build: .
    container_name: fitmarket-server_c
    ports:
      - "5988:5988"
    networks:
      - web
    volumes:
      - .:/app
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    depends_on:
      - mongo
    restart: always
    
  mongoData:
    image: mongo
    command: mongod --bind_ip_all
    container_name: mongo_c
    ports:
      - "27018:27017"  
    networks:
      - web
    deploy:
      mode: replicated 
      replicas: 1
    volumes:
      - mongoData:/data/db 


networks:
  web:
    external: true    #else ude driver: overlay

volumes:
  mongoData: {}
