version: "3"

services:
  frontend:
    build: ./frontend
    container_name: ecom-client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network


  backend:
    build: .
    container_name: ecom-server
    restart: always
    ports:
      - "5987:5987"
    networks:
      - mern-network
  
networks:
  mern-network:
    driver: bridge